const obj = {
    "id": "6dd89cee-dfce-42d0-962f-60bf42a4b084",
    "gender": "M",
    "date_of_birth": "1960-02-03",
    "date_of_death": null,
    "label": "McMorrow, John DOB: 03/Feb/1960 (Male)",
    "first_name": "John",
    "family_name": "McMorrow",
    "consents": ["consent"],
    "frozen": false,
    "locked": false,
    "patient_id": "345",
    "created_date": "2020-03-03T15:10:39.376242Z",
    "updated_date": "2020-03-03T15:10:39.702680Z",
    "enrol_date": "2020-02-04",
    "end_date": null,
    "consent_date": null,
    "status": "active",
    "review_pending": false,
    "reviewed_date": null,
    "accepted": true,
    "qb_consents": {"consent": true},
    "study": "67385377-9514-4104-b6c3-27d20a79132b",
    "record": "57962105-27e7-421a-9007-54f738f1d347",
    "created_by": 745543738,
    "reviewed_by": null,
    "start_date": "2020-02-04",
    "editable": false,
    "middle_name": null,
    "guid_first_name": null,
    "guid_family_name": null,
    "city_of_birth": null,
    "country_of_birth": null,
    "national_id": null,
    "guid_date_of_birth": null,
    "country_of_residence": null,
    "contact_carer": null,
    "carer_name": null,
    "carer_email": null,
    "carer_mobile": null,
    "carer_mobile2": null,
    "carer_address": null,
    "carer_preferred_language": null,
    "contact_patient": null,
    "patient_email": null,
    "patient_mobile": null,
    "patient_mobile2": null,
    "patient_address": null,
    "patient_postal_address": null,
    "patient_preferred_language": null,
    "fathers_first_name": null,
    "fathers_middle_name": null,
    "fathers_family_name": null,
    "mothers_first_name": null,
    "mothers_middle_name": null,
    "mothers_family_name": null,
    "guardian_first_name": null,
    "guardian_middle_name": null,
    "guardian_family_name": null,
    "secondary_studies": [],
    "identifiers": {"study_id": "345"},
    "metadata": {
        "0c4dad36-b571-4819-899c-9ad9cff2f78a": {
            "bool_value": true,
            "date_value": "2020-02-26",
            "text_value": null,
            "consent_version": null,
            "consent_type": null
        }
    },
    "secondary_metadata": {},
    "shared": false
}

export const EDC_CASEBOOK = obj;
